[allgemein]
title=Ernährungstagebuch
host=0.0.0.0
port=9001
storage_secret=ein_sehr_langer_secret_key_der_niemals_veraendert_wird
; Quelle der Instanz: 'dev' fuer Entwicklung, 'prod' fuer Installation
quelle=dev

[couchdb]
server_url = http://192.168.178.123:5984
database = ernaehrungstagebuch
username = admin
password = ein_sicheres_passwort_fuer_couchdb
